// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"demo/api/controller"
	user3 "demo/api/controller/user"
	"demo/api/router"
	"demo/cmd/http_server"
	"demo/internal/storage/user"
	user2 "demo/internal/usecase/user"
)

// Injectors from wire.go:

func initServer() *httpserver.Server {
	userStorage := user.New()
	userUsecase := user2.New(userStorage)
	userCtrl := user3.New(userUsecase)
	controllerController := controller.New(userCtrl)
	routerRouter := router.New(controllerController)
	server := httpserver.New(routerRouter)
	return server
}
